### ISSUE TITLE
record.json的读入问题

### ISSUE THREAD

**Issue by xia-i** [Billyzou0741326/bilibili-live-monitor-ts#53]
record.json在运行开始读入的时候好像会自动删除，运行中有礼物才会重新存入
先前的记录就没有了
不懂nodejs，我也不知道我说的对不对

**Comment by xia-i** [comment]
测试了下，确实是我说的情况，读取完后会自动删除
先前的记录不会被重新写入，也就是重启后就不会加载先前的房间了

**Comment by Billyzou0741326** [comment]
我这边没有测出`build/db/record.json`在读取完之后删除的情况
能详细描述一下观测结果吗

**Comment by xia-i** [comment]
就是重新运行几分钟后，几千条的记录会变成几条(这几条是这几分钟内房间里有礼物写出来的)
准确的说不是删除，是清空了。但是原先记录有的房间是连上了的

**Comment by Billyzou0741326** [comment]
这个算是预期中的行为了 这行的3天过滤改成300天之类的 就不会有这种情况了吧
https://github.com/Billyzou0741326/bilibili-live-monitor-ts/blob/bb473d87a03e75191b849ee5e80d44d97f82b332/src/settings.json#L41
https://github.com/Billyzou0741326/bilibili-live-monitor-ts/blob/bb473d87a03e75191b849ee5e80d44d97f82b332/build/settings.json#L41

**Comment by xia-i** [comment]
问题是原先记录中的updated_at全是在有效时间内的

**Comment by xia-i** [comment]
在本地windows和服务器centos7都测试了，不管updated_at有没有到期，它就是一律全清空不会保留先前的记录

**Comment by xia-i** [comment]
并不是一打开就马上清空，是过了几分钟，看情况应该是定时器几分钟写一次，没有加载原先的列表

**Comment by Billyzou0741326** [comment]
已测 复现了

**Comment by Billyzou0741326** [comment]
感谢反馈 此前观测到过同样的问题 当时没深究
